from random import choice
from typing import List


def chooseQuotes() -> str:
    """Return a random quote."""
    quotes = [
        "FIRST!111!!!11!!1!1",
        "Heya~",
        "Mewo",
        "Made with love and sulfuric acid",
        "Powered by nuclear energy",
        "See? I have the sun!",
        "A story, like thousands other stories",
        "you found me. Why?",
        "Fish!",
        "So you woke up in an unfamiliar, dark location?",
        "p a n c a k e s",
        "You only have one shot",
        "Hey guys...",
        "GEOMETRY DASH REFERENCE?!?!??!",
        "Send dolors or explod",
        "Just the two of us",
        "We can make it if we try",
        "Fries are really yummy",
        "Rule number 43: No edging",
        "As seen on wired",
        "Softpedia certified",
        "Thanks for the support!",
        "l lI ll l_",
        "Also try revanced",
        "Over 100k downloads",
        "eXplod",
        "Welcome, friend",
        "Welcome to NGINX!",
        "Yippee",
        "As seen on notrodan",
        "My cabron monoxied alamr boke",
        "LiveLeak",
        "Elon musk is really not a good person",
        "Spoinkbub",
        "BIG MEN",
        "** siggy **",
        "I ransomeware",
        "Hey, how do I unzip a RAR file??",
        "TWITTER, TWITTER FOR ANDROID",
        "How to become shrigma male tutorial | RAREST MALE TYPE!?",
        "Trans right!",
        "WhyCantITypeSpaces",
        "explod thabks",
        "tetris moment",
        "I identify as kilometers per second because I want to km/s",
        "WhatDoYouMeanShellShattered?!",
        "Cancelled.",
        ":trolley:",
        "luftvärnskanonvagn",
        "No bobucks?",
        "UwU. *Steals your toast*",
        "A new update is available!",
        "509gb",
        "FREE BOBUX GENERATOR!?!?!",
        "sorry can't help it just a scorpio",
        '"bitch" -@danilwhale',
        '"xtooblox made me pregnant" -@editdev',
        '"basketmball" -@cute.eeper',
        "UEE 😭🥺💧Eu💧 💧 E E 😭😭 E EUE 🥺🥺😭 UUUU 😭🥺💧🥺😭ue💧 ee😭🥺💧 ue🥺 e e e😭. e💧🥺😭Uueuuue.",
        "polugon dunute >:3",
        "spotify album 2gANfR09MoBGPXKqYPTGw7"
        "Hi I have a Pixel 4a grapheneos and I need to make Discord most privacy friendly and secure as...",
        "Hey Ya!",
        '"do not consider doing web dev it is not worth it" - @jenku',
        "PREPARE THYSELF",
        "THY END IS NOW",
        "plap guy...",
        "gayass? i find it quite straight",
        '"amogus" -@martinishere',
    ]
    return choice(quotes)


footers: List[str] = ["H - Help", "^C - Exit", "N/B - Pages"]

columns: List[List[List[str]]] = [
    ["bamboozled", "code", "broke", "down"],
    [["d", "Debloat"], ["t", "Tweaks"], ["c", "Cleaning"], ["a", "Apps"]],
    [["l", "Linux"], ["w", "Windows"], ["m", "OS Mods"], ["a", "Apps"]],
    [
        ["l", "Minecraft Launchers"],
        ["g", "Game Launchers"],
        ["r", "Redists"],
        ["a", "Apps"],
    ],
]
